"""Error codes shared by backend and Agent.

15 codes come from SRS v7.3. The other 14 are additions NOT in the SRS (decision D-030);
each carries `# not in SRS v7.3`.
"""

from enum import StrEnum


class ErrorCode(StrEnum):
    # --- SRS v7.3 ---
    TALLY_SERVER_DISABLED = "TALLY_SERVER_DISABLED"
    TDL_NOT_LOADED = "TDL_NOT_LOADED"
    COMPANY_NOT_LOADED = "COMPANY_NOT_LOADED"
    COMPANY_MISMATCH = "COMPANY_MISMATCH"
    TALLY_EXPORT_TIMEOUT = "TALLY_EXPORT_TIMEOUT"
    QUEUE_FULL = "QUEUE_FULL"
    SYNC_LOCKED = "SYNC_LOCKED"
    STALE_ALTERID = "STALE_ALTERID"
    CREDENTIAL_INVALID = "CREDENTIAL_INVALID"
    AGENT_REVOKED = "AGENT_REVOKED"
    UDF_NOT_FOUND = "UDF_NOT_FOUND"
    UNRESOLVED_GROUP = "UNRESOLVED_GROUP"
    UNSUPPORTED_ALLOCATION_TYPE = "UNSUPPORTED_ALLOCATION_TYPE"
    UNLINKED_CREDIT_NOTE = "UNLINKED_CREDIT_NOTE"
    UNLINKED_DEBIT_NOTE = "UNLINKED_DEBIT_NOTE"
    # --- additions, see D-030 ---
    TALLY_UNREACHABLE = "TALLY_UNREACHABLE"  # not in SRS v7.3
    DEBIT_CREDIT_IMBALANCE = "DEBIT_CREDIT_IMBALANCE"  # not in SRS v7.3
    UNKNOWN_MASTER_REFERENCE = "UNKNOWN_MASTER_REFERENCE"  # not in SRS v7.3
    PARSE_ERROR = "PARSE_ERROR"  # not in SRS v7.3
    AGENT_SELECTION_REQUIRED = "AGENT_SELECTION_REQUIRED"  # not in SRS v7.3
    AGENT_INCOMPATIBLE = "AGENT_INCOMPATIBLE"  # not in SRS v7.3
    INVALID_COMMAND_STATE = "INVALID_COMMAND_STATE"  # not in SRS v7.3
    KEY_LIST_SUSPICIOUS = "KEY_LIST_SUSPICIOUS"  # not in SRS v7.3
    GATE_NOT_PASSED = "GATE_NOT_PASSED"  # not in SRS v7.3
    VALIDATION_ERROR = "VALIDATION_ERROR"  # not in SRS v7.3
    NOT_AUTHENTICATED = "NOT_AUTHENTICATED"  # not in SRS v7.3
    FORBIDDEN = "FORBIDDEN"  # not in SRS v7.3
    NOT_FOUND = "NOT_FOUND"  # not in SRS v7.3
    CONFLICT = "CONFLICT"  # not in SRS v7.3


SRS_CODES: tuple[ErrorCode, ...] = tuple(list(ErrorCode)[:15])
PROPOSED_CODES: tuple[ErrorCode, ...] = tuple(list(ErrorCode)[15:])
