"""User-defined fields (SRS 5.11, DR-UDF-1..4).

Nothing is extracted by default (DR-UDF-1): the base TDL has no UDF fields. Owners/Admins add
mappings; `generate_tdl` turns them into a TDL include (DR-UDF-4: generated, never hand-edited)
and `UdfReader` reads the values into `custom_fields`. How Tally exposes a UDF (`$Name`) is a
draft until GATE-G22 passes.
"""

import re
import xml.etree.ElementTree as ET
from datetime import date
from decimal import Decimal
from enum import StrEnum
from typing import Self

from pydantic import BaseModel, ConfigDict, field_validator, model_validator

from tally_contract import tally_constants as tc
from tally_contract.enums import CollectionType
from tally_contract.errors import ErrorCode
from tally_contract.log import get_logger
from tally_contract.values import parse_bool, parse_date, parse_plain_decimal, text

log = get_logger(__name__)

# Our record lines in tdl/TallyAnalytics.tdl that the include extends (tested).
UDF_LINES: dict[CollectionType, str] = {
    CollectionType.LEDGER: "TA_LedgersLine",
    CollectionType.STOCK_ITEM: "TA_StockItemsLine",
    CollectionType.VOUCHER: "TA_VchLine",
}
_TDL_IDENTIFIER = re.compile(r"^[A-Za-z][A-Za-z0-9_]{0,63}$")
_FIELD_KEY = re.compile(r"^[a-z][a-z0-9_]{0,62}$")

UdfValue = str | Decimal | date | bool | None


class UdfType(StrEnum):
    TEXT = "TEXT"
    NUMBER = "NUMBER"
    DATE = "DATE"
    LOGICAL = "LOGICAL"


class UdfMapping(BaseModel):
    """One row of custom_field_mappings (SRS 5.10)."""

    model_config = ConfigDict(frozen=True, extra="forbid")
    collection_type: CollectionType
    tally_field: str
    field_key: str
    data_type: UdfType

    @field_validator("tally_field")
    @classmethod
    def _identifier(cls, value: str) -> str:
        # The generated include is loaded into the customer's Tally: only a bare identifier.
        if not _TDL_IDENTIFIER.fullmatch(value):
            raise ValueError("tally_field must be a TDL identifier (letters, digits, _)")
        return value

    @field_validator("field_key")
    @classmethod
    def _key(cls, value: str) -> str:
        if not _FIELD_KEY.fullmatch(value):
            raise ValueError("field_key must be snake_case")
        return value

    @model_validator(mode="after")
    def _collection(self) -> Self:
        if self.collection_type not in UDF_LINES:
            raise ValueError(f"custom fields are not supported on {self.collection_type}")
        return self

    @property
    def tdl_field(self) -> str:
        return f"TA_UDF_{self.collection_type.value}_{self.field_key}"

    @property
    def xml_tag(self) -> str:
        return f"UDF_{self.field_key.upper()}"


def _unique(mappings: list[UdfMapping]) -> list[UdfMapping]:
    keys = [(m.collection_type, m.field_key) for m in mappings]
    if len(set(keys)) != len(keys):
        raise ValueError("a field_key is mapped twice for the same collection")
    return sorted(mappings, key=lambda m: (m.collection_type.value, m.field_key))


def generate_tdl(mappings: list[UdfMapping]) -> str:
    """The TDL include adding the mapped fields to our reports (DR-UDF-4). Deterministic."""
    ordered = _unique(mappings)
    lines = [
        ";; Generated by tally_contract.udf from custom_field_mappings (DR-UDF-4). Do not edit.",
        f";; For TallyAnalytics.tdl {tc.TDL_VERSION}. Load it after TallyAnalytics.tdl.",
    ]
    for collection, line in UDF_LINES.items():
        fields = [m for m in ordered if m.collection_type == collection]
        if not fields:
            continue
        lines += [
            "",
            f"[#Line: {line}]",
            f"    Add : Fields : {', '.join(m.tdl_field for m in fields)}",
        ]
        for m in fields:
            lines += [
                "",
                f"[Field: {m.tdl_field}]",
                "    Use    : Name Field",
                f"    Set As : $$String:${m.tally_field}    ;; GATE-G22",
                f'    XMLTag : "{m.xml_tag}"',
            ]
    return "\n".join(lines) + "\n"


class UdfReader:
    """Reads mapped values into custom_fields. Create one per sync run: a mapped field missing
    from the export is logged once per run as UDF_NOT_FOUND (DR-UDF-3); the sync continues."""

    def __init__(self, mappings: list[UdfMapping]) -> None:
        self._by_collection: dict[CollectionType, list[UdfMapping]] = {}
        for m in _unique(mappings):
            self._by_collection.setdefault(m.collection_type, []).append(m)
        self._warned: set[tuple[CollectionType, str]] = set()

    def read(self, collection: CollectionType, element: ET.Element) -> dict[str, UdfValue]:
        values: dict[str, UdfValue] = {}
        for m in self._by_collection.get(collection, []):
            node = element.find(m.xml_tag)
            if node is None:
                values[m.field_key] = None
                self._missing(m)
                continue
            values[m.field_key] = _typed(m, node.text)
        return values

    def _missing(self, m: UdfMapping) -> None:
        key = (m.collection_type, m.field_key)
        if key in self._warned:
            return
        self._warned.add(key)
        log.warning(
            "udf_not_found",
            code=ErrorCode.UDF_NOT_FOUND.value,
            collection_type=m.collection_type.value,
            field_key=m.field_key,
            tally_field=m.tally_field,
        )


def _typed(m: UdfMapping, raw: str | None) -> UdfValue:
    """A malformed value fails the record (ValueError); nothing is guessed."""
    if text(raw) is None:
        return None
    match m.data_type:
        case UdfType.TEXT:
            return text(raw)
        case UdfType.NUMBER:
            return parse_plain_decimal(raw)
        case UdfType.DATE:
            return parse_date(raw)
        case UdfType.LOGICAL:
            return parse_bool(raw)
