"""Map SRS requirement IDs to the tests that prove them (P0.9, SRS 25).

Reads requirement IDs from docs/srs/SRS_v7_3.md, collects `@pytest.mark.req(...)` (the test fully
proves the requirement) and `@pytest.mark.req_partial(...)` (it proves only part) from the test
tree, and writes docs/traceability.md. Partial coverage is listed separately and never counts as
covered. Non-blocking until P16, where it becomes a gate.

    uv run python -m tally_tools.traceability [--check]
"""

import argparse
import ast
import re
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).parents[2]
SRS = ROOT / "docs/srs/SRS_v7_3.md"
DEST = ROOT / "docs/traceability.md"
TEST_DIRS = ("shared/tests", "backend/tests", "agent/tests", "tools/tests")

# SRS requirement prefixes (phase-00 P0.9). Longest first so FR-STK-1 never matches as FR-1.
PREFIXES = (
    "FR-AGE",
    "FR-PAY",
    "FR-STK",
    "FR-DD",
    "FR",
    "AGT",
    "RTE",
    "VER",
    "SYNC",
    "VAL",
    "DR",
    "ACC",
    "REC",
    "AGE",
    "EXP",
    "RBAC",
    "SEC",
    "LOG",
    "PERF",
    "NFR",
    "TZ",
    "Q",
    "BKP",
    "TEST",
    "TOPN",
    "AC",
)
ID_RE = re.compile(rf"\b(?:{'|'.join(PREFIXES)})(?:-[A-Z]+)*-\d+(?:\.\d+)*\b")


def requirement_ids(srs_text: str) -> list[str]:
    seen: dict[str, None] = {}
    for match in ID_RE.findall(srs_text):
        seen.setdefault(match, None)
    return list(seen)


def markers_by_id(
    test_root: Path, dirs: tuple[str, ...] = TEST_DIRS, marker: str = "req"
) -> dict[str, list[str]]:
    """{requirement id: ["path::test_name", ...]} from @pytest.mark.<marker>(...) decorators."""
    found: dict[str, list[str]] = defaultdict(list)
    for directory in dirs:
        for path in sorted((test_root / directory).rglob("test_*.py")):
            tree = ast.parse(path.read_text(encoding="utf-8"))
            for node in ast.walk(tree):
                if not isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
                    continue
                for deco in node.decorator_list:
                    if not isinstance(deco, ast.Call):
                        continue
                    attr = deco.func
                    if not (isinstance(attr, ast.Attribute) and attr.attr == marker):
                        continue
                    for arg in deco.args:
                        if isinstance(arg, ast.Constant) and isinstance(arg.value, str):
                            rel = path.relative_to(test_root)
                            found[arg.value].append(f"{rel}::{node.name}")
    return dict(found)


def render(ids: list[str], tests: dict[str, list[str]], partial: dict[str, list[str]]) -> str:
    """`tests`: full-coverage markers; `partial`: req_partial markers."""
    covered = [i for i in ids if i in tests]
    partly = [i for i in ids if i not in tests and i in partial]
    missing = [i for i in ids if i not in tests and i not in partial]
    unknown = sorted((set(tests) | set(partial)) - set(ids))
    lines = [
        "# Requirement traceability (SRS 25)",
        "",
        "Generated by `make traceability`; do not edit by hand. A requirement is covered only when",
        "a test marked `@pytest.mark.req` fully proves it; `@pytest.mark.req_partial` tests are",
        "listed separately and never count as covered (CLAUDE.md).",
        "",
        f"- Requirement IDs in the SRS: **{len(ids)}**",
        f"- Fully covered by at least one test: **{len(covered)}**",
        f"- Partially covered only: **{len(partly)}**",
        f"- Not covered yet: **{len(missing)}**",
        "",
        "## Covered",
        "",
        "| Requirement | Tests |",
        "|---|---|",
    ]
    lines += [f"| {i} | {'<br>'.join(tests[i])} |" for i in covered]
    lines += [
        "",
        "## Partially covered (not counted as covered)",
        "",
        "| Requirement | Tests proving part of it |",
        "|---|---|",
    ]
    lines += [f"| {i} | {'<br>'.join(partial[i])} |" for i in partly]
    lines += ["", "## Not covered yet", "", ", ".join(missing) if missing else "_none_", ""]
    if unknown:
        lines += [
            "## Marked in tests but not found in the SRS",
            "",
            "These are additions (see `docs/decisions.md`) or typos.",
            "",
            ", ".join(unknown),
            "",
        ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if any requirement has no test")
    args = parser.parse_args()
    ids = requirement_ids(SRS.read_text(encoding="utf-8"))
    tests = markers_by_id(ROOT)
    partial = markers_by_id(ROOT, marker="req_partial")
    DEST.write_text(render(ids, tests, partial), encoding="utf-8", newline="\n")
    missing = [i for i in ids if i not in tests]  # partial coverage does not count
    if args.check and missing:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
