"""Map SRS requirement IDs to the tests that prove them (P0.9, SRS 25).

Reads requirement IDs from docs/srs/SRS_v7_3.md, collects `@pytest.mark.req(...)` (the test fully
proves the requirement) and `@pytest.mark.req_partial(...)` (it proves only part) from the test
tree, and writes docs/traceability.md. Partial coverage is listed separately and never counts as
covered. Non-blocking until P16, where it becomes a gate.

    uv run python -m tally_tools.traceability [--check]
"""

import argparse
import ast
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).parents[2]
SRS = ROOT / "docs/srs/SRS_v7_3.md"
DEST = ROOT / "docs/traceability.md"
MANUAL = ROOT / "docs/manual-verification.md"
TEST_DIRS = ("shared/tests", "backend/tests", "agent/tests", "tools/tests")

# SRS requirement prefixes (phase-00 P0.9). Longest first so FR-STK-1 never matches as FR-1.
PREFIXES = (
    "FR-AGE",
    "FR-PAY",
    "FR-STK",
    "FR-DD",
    "FR",
    "AGT",
    "RTE",
    "VER",
    "SYNC",
    "VAL",
    "DR",
    "ACC",
    "REC",
    "AGE",
    "EXP",
    "RBAC",
    "SEC",
    "LOG",
    "PERF",
    "NFR",
    "TZ",
    "Q",
    "BKP",
    "TEST",
    "TOPN",
    "AC",
)
# (?!\.\w) rejects a group reference: the SRS writes "FR-1.x" and "SEC-1.x" in its own
# architecture tables, and without this the regex takes "FR-1" out of them and reports 28
# section headings as uncovered requirements (P16.9).
ID_RE = re.compile(rf"\b(?:{'|'.join(PREFIXES)})(?:-[A-Z]+)*-\d+(?:\.\d+)*(?!\.\w)\b")


def requirement_ids(srs_text: str) -> list[str]:
    seen: dict[str, None] = {}
    for match in ID_RE.findall(srs_text):
        seen.setdefault(match, None)
    return list(seen)


def markers_by_id(
    test_root: Path, dirs: tuple[str, ...] = TEST_DIRS, marker: str = "req"
) -> dict[str, list[str]]:
    """{requirement id: ["path::test_name", ...]} from @pytest.mark.<marker>(...) decorators."""
    found: dict[str, list[str]] = defaultdict(list)
    for directory in dirs:
        for path in sorted((test_root / directory).rglob("test_*.py")):
            tree = ast.parse(path.read_text(encoding="utf-8"))
            for node in ast.walk(tree):
                if not isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
                    continue
                for deco in node.decorator_list:
                    if not isinstance(deco, ast.Call):
                        continue
                    attr = deco.func
                    if not (isinstance(attr, ast.Attribute) and attr.attr == marker):
                        continue
                    for arg in deco.args:
                        if isinstance(arg, ast.Constant) and isinstance(arg.value, str):
                            rel = path.relative_to(test_root)
                            found[arg.value].append(f"{rel}::{node.name}")
    return dict(found)


def manual_entries(path: Path = MANUAL) -> dict[str, tuple[str, str]]:
    """{requirement id: (why it cannot be a test, what it waits for or "" if verified)}.

    Some requirements cannot be a test in this repository: TLS at the proxy, a Windows service,
    an installer, a figure an accountant must agree with. P16.9 makes the gate blocking, so each
    of those needs an entry here saying why, and either the evidence or what it waits for -
    rather than being silently absent, which is what the gate exists to stop.

    The table's first column is the id and its last is the blocker (`-` when none).
    """
    if not path.is_file():
        return {}
    found: dict[str, tuple[str, str]] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.startswith("| "):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 4 or not ID_RE.fullmatch(cells[0]):
            continue
        blocker = cells[3]
        found[cells[0]] = (cells[1], "" if blocker in {"-", "—", ""} else blocker)
    return found


def render(
    ids: list[str],
    tests: dict[str, list[str]],
    partial: dict[str, list[str]],
    manual: dict[str, tuple[str, str]] | None = None,
) -> str:
    """`tests`: full-coverage markers; `partial`: req_partial markers; `manual`: entries in
    docs/manual-verification.md, mapping an id to its blocker (or "" when verified by hand)."""
    manual = manual or {}
    covered = [i for i in ids if i in tests]
    by_hand = [i for i in ids if i not in tests and i in manual and not manual[i][1]]
    blocked = [i for i in ids if i not in tests and i in manual and manual[i][1]]
    accounted = set(covered) | set(by_hand) | set(blocked)
    partly = [i for i in ids if i not in accounted and i in partial]
    missing = [i for i in ids if i not in accounted and i not in partial]
    unknown = sorted((set(tests) | set(partial)) - set(ids))
    stale = sorted(set(manual) - set(ids))
    lines = [
        "# Requirement traceability (SRS 25)",
        "",
        "Generated by `make traceability`; do not edit by hand. A requirement is covered only when",
        "a test marked `@pytest.mark.req` fully proves it; `@pytest.mark.req_partial` tests are",
        "listed separately and never count as covered (CLAUDE.md).",
        "",
        "Since P16.9 `make traceability CHECK=1` is a CI gate. A requirement is **accounted for**",
        "by a test, or by an entry in [manual-verification.md](manual-verification.md) — which",
        "may say it is verified by hand, or name what it is blocked on. Blocked entries are listed",
        "separately below and are **not** verified: they are what the acceptance run (P16.10) has",
        "left to do.",
        "",
        f"- Requirement IDs in the SRS: **{len(ids)}**",
        f"- Fully covered by at least one test: **{len(covered)}**",
        f"- Verified by hand: **{len(by_hand)}**",
        f"- Accounted for but **not yet verified** (blocked): **{len(blocked)}**",
        f"- Partially covered only: **{len(partly)}**",
        f"- Not accounted for at all: **{len(missing)}**",
        "",
        "## Covered",
        "",
        "| Requirement | Tests |",
        "|---|---|",
    ]
    lines += [f"| {i} | {'<br>'.join(tests[i])} |" for i in covered]
    lines += [
        "",
        "## Partially covered (not counted as covered)",
        "",
        "| Requirement | Tests proving part of it |",
        "|---|---|",
    ]
    lines += [f"| {i} | {'<br>'.join(partial[i])} |" for i in partly]
    lines += [
        "",
        "## Verified by hand (manual-verification.md)",
        "",
        "| Requirement | Why it cannot be a test |",
        "|---|---|",
    ]
    lines += [f"| {i} | {manual[i][0]} |" for i in by_hand]
    lines += [
        "",
        "## Accounted for but not yet verified",
        "",
        "Each has an entry in manual-verification.md naming what it waits for.",
        "",
        "| Requirement | Waiting for |",
        "|---|---|",
    ]
    lines += [f"| {i} | {manual[i][1]} |" for i in blocked]
    lines += ["", "## Not accounted for at all", ""]
    lines += [", ".join(missing) if missing else "_none_", ""]
    if stale:
        lines += [
            "## In manual-verification.md but not in the SRS",
            "",
            "Remove these, or correct the id.",
            "",
            ", ".join(stale),
            "",
        ]
    if unknown:
        lines += [
            "## Marked in tests but not found in the SRS",
            "",
            "These are additions (see `docs/decisions.md`) or typos.",
            "",
            ", ".join(unknown),
            "",
        ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if any requirement has no test")
    args = parser.parse_args()
    ids = requirement_ids(SRS.read_text(encoding="utf-8"))
    tests = markers_by_id(ROOT)
    partial = markers_by_id(ROOT, marker="req_partial")
    manual = manual_entries()
    DEST.write_text(render(ids, tests, partial, manual), encoding="utf-8", newline="\n")
    # The gate's question is "is this requirement tracked?", not "is it done?". Three things
    # answer it: a `req` test, a `req_partial` test (which carries a comment naming what is
    # missing and where it will be proven), or an entry in manual-verification.md. None of that
    # makes a partial test *covered* - CLAUDE.md is explicit, and the report above keeps the
    # buckets apart - but an id with a partial test is not an id nobody has looked at, which is
    # what this gate exists to catch. What fails it is a requirement with none of the three.
    missing = [i for i in ids if i not in tests and i not in partial and i not in manual]
    stale = sorted(set(manual) - set(ids))
    if args.check and (missing or stale):
        for requirement in missing:
            sys.stderr.write(
                f"{requirement}: no test and no entry in docs/manual-verification.md\n"
            )
        for requirement in stale:
            sys.stderr.write(f"{requirement}: in manual-verification.md but not in the SRS\n")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
