"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-23
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tally_guid', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('financial_year_start', sa.Date(), nullable=False),
    sa.Column('company_timezone', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('company_id', name=op.f('pk_companies')),
    sa.UniqueConstraint('tally_guid', name=op.f('uq_companies_tally_guid'))
    )
    op.create_table('roles',
    sa.Column('role_id', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('role_name', sa.Text(), nullable=False),
    sa.CheckConstraint("role_name IN ('OWNER', 'ACCOUNTANT', 'ADMIN')", name=op.f('ck_roles_role_name')),
    sa.PrimaryKeyConstraint('role_id', name=op.f('pk_roles')),
    sa.UniqueConstraint('role_name', name=op.f('uq_roles_role_name'))
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users'))
    )
    op.create_index('uq_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('fk_user_roles_company_id')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], name=op.f('fk_user_roles_role_id')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_user_roles_user_id')),
    sa.PrimaryKeyConstraint('user_id', 'company_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_index(op.f('ix_user_roles_company_id'), 'user_roles', ['company_id'], unique=False)
    # ### end Alembic commands ###
    _upgrade_extras()


def downgrade() -> None:
    _downgrade_extras()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_roles_company_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index('uq_users_email_lower', table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('companies')
    # ### end Alembic commands ###


# --- hand-written: seeds, triggers and grants (autogenerate cannot express them) ---


def _upgrade_extras() -> None:
    roles = sa.table("roles", sa.column("role_id", sa.SmallInteger), sa.column("role_name"))
    op.bulk_insert(
        roles,
        [
            {"role_id": 1, "role_name": "OWNER"},
            {"role_id": 2, "role_name": "ACCOUNTANT"},
            {"role_id": 3, "role_name": "ADMIN"},
        ],
    )


def _downgrade_extras() -> None:
    pass
