"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-23
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tally_guid', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('financial_year_start', sa.Date(), nullable=False),
    sa.Column('company_timezone', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('company_id', name=op.f('pk_companies')),
    sa.UniqueConstraint('tally_guid', name=op.f('uq_companies_tally_guid'))
    )
    op.create_table('roles',
    sa.Column('role_id', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('role_name', sa.Text(), nullable=False),
    sa.CheckConstraint("role_name IN ('OWNER', 'ACCOUNTANT', 'ADMIN')", name=op.f('ck_roles_role_name')),
    sa.PrimaryKeyConstraint('role_id', name=op.f('pk_roles')),
    sa.UniqueConstraint('role_name', name=op.f('uq_roles_role_name'))
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users'))
    )
    op.create_index('uq_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('agent_registration_tokens',
    sa.Column('token_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('fk_agent_registration_tokens_company_id')),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name=op.f('fk_agent_registration_tokens_created_by')),
    sa.PrimaryKeyConstraint('token_id', name=op.f('pk_agent_registration_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_agent_registration_tokens_token_hash'))
    )
    op.create_index(op.f('ix_agent_registration_tokens_company_id'), 'agent_registration_tokens', ['company_id'], unique=False)
    op.create_table('agents',
    sa.Column('agent_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.Text(), nullable=False),
    sa.Column('credential_hash', sa.Text(), nullable=True),
    sa.Column('credential_salt', sa.LargeBinary(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('tally_guid', sa.Text(), nullable=True),
    sa.Column('tally_company_name', sa.Text(), nullable=True),
    sa.Column('tally_host', sa.Text(), nullable=True),
    sa.Column('tally_port', sa.Integer(), nullable=True),
    sa.Column('extraction_batch_size', sa.Integer(), nullable=True),
    sa.Column('agent_version', sa.Text(), nullable=True),
    sa.Column('tdl_version', sa.Text(), nullable=True),
    sa.Column('tally_version', sa.Text(), nullable=True),
    sa.Column('tally_uptime_seconds', sa.BigInteger(), nullable=True),
    sa.Column('queue_status', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_tally_status', sa.Text(), nullable=True),
    sa.Column('tally_status_since', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("last_tally_status IN ('OK', 'TALLY_UNREACHABLE', 'TALLY_SERVER_DISABLED', 'TDL_NOT_LOADED', 'COMPANY_NOT_LOADED', 'COMPANY_MISMATCH')", name=op.f('ck_agents_last_tally_status')),
    sa.CheckConstraint("status IN ('REGISTERING', 'ACTIVE', 'OFFLINE', 'INCOMPATIBLE', 'REVOKED')", name=op.f('ck_agents_status')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('fk_agents_company_id')),
    sa.PrimaryKeyConstraint('agent_id', name=op.f('pk_agents')),
    sa.UniqueConstraint('company_id', 'agent_id', name=op.f('uq_agents_company_id_agent_id')),
    sa.UniqueConstraint('company_id', 'agent_name', name=op.f('uq_agents_company_id_agent_name'))
    )
    op.create_index(op.f('ix_agents_company_id'), 'agents', ['company_id'], unique=False)
    op.create_table('cost_centres',
    sa.Column('cost_centre_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tally_guid', sa.Text(), nullable=False),
    sa.Column('alter_id', sa.BigInteger(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('ACTIVE', 'MISSING_IN_TALLY', 'INACTIVE')", name=op.f('ck_cost_centres_status')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('fk_cost_centres_company_id')),
    sa.PrimaryKeyConstraint('cost_centre_id', name=op.f('pk_cost_centres')),
    sa.UniqueConstraint('company_id', 'cost_centre_id', name=op.f('uq_cost_centres_company_id_cost_centre_id')),
    sa.UniqueConstraint('company_id', 'tally_guid', name=op.f('uq_cost_centres_company_id_tally_guid'))
    )
    op.create_table('groups',
    sa.Column('group_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('parent_group_id', sa.UUID(), nullable=True),
    sa.Column('parent_tally_guid', sa.Text(), nullable=True),
    sa.Column('predefined_group_id', sa.UUID(), nullable=True),
    sa.Column('classification_group_id', sa.UUID(), nullable=True),
    sa.Column('primary_group_id', sa.UUID(), nullable=True),
    sa.Column('nature', sa.Text(), nullable=True),
    sa.Column('is_predefined', sa.Boolean(), nullable=False),
    sa.Column('reserved_name', sa.Text(), nullable=True),
    sa.Column('resolution_status', sa.Text(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tally_guid', sa.Text(), nullable=False),
    sa.Column('alter_id', sa.BigInteger(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("nature IN ('ASSET', 'LIABILITY', 'INCOME', 'EXPENSE')", name=op.f('ck_groups_nature')),
    sa.CheckConstraint("resolution_status <> 'RESOLVED' OR (classification_group_id IS NOT NULL AND nature IS NOT NULL)", name=op.f('ck_groups_resolved_has_anchor')),
    sa.CheckConstraint("resolution_status IN ('RESOLVED', 'UNRESOLVED_GROUP')", name=op.f('ck_groups_resolution_status')),
    sa.CheckConstraint("status IN ('ACTIVE', 'MISSING_IN_TALLY', 'INACTIVE')", name=op.f('ck_groups_status')),
    sa.ForeignKeyConstraint(['company_id', 'classification_group_id'], ['groups.company_id', 'groups.group_id'], name=op.f('fk_groups_company_id_classification_group_id')),
    sa.ForeignKeyConstraint(['company_id', 'parent_group_id'], ['groups.company_id', 'groups.group_id'], name=op.f('fk_groups_company_id_parent_group_id')),
    sa.ForeignKeyConstraint(['company_id', 'predefined_group_id'], ['groups.company_id', 'groups.group_id'], name=op.f('fk_groups_company_id_predefined_group_id')),
    sa.ForeignKeyConstraint(['company_id', 'primary_group_id'], ['groups.company_id', 'groups.group_id'], name=op.f('fk_groups_company_id_primary_group_id')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('fk_groups_company_id')),
    sa.PrimaryKeyConstraint('group_id', name=op.f('pk_groups')),
    sa.UniqueConstraint('company_id', 'group_id', name=op.f('uq_groups_company_id_group_id')),
    sa.UniqueConstraint('company_id', 'tally_guid', name=op.f('uq_groups_company_id_tally_guid'))
    )
    op.create_index(op.f('ix_groups_primary_group_id'), 'groups', ['primary_group_id'], unique=False)
    op.create_index('uq_groups_company_id_reserved_name', 'groups', ['company_id', 'reserved_name'], unique=True, postgresql_where=sa.text('reserved_name IS NOT NULL'))
    op.create_table('reconciliation_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('tally_value', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('local_value', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('absolute_difference', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('percentage_difference', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('result', sa.Text(), nullable=False),
    sa.CheckConstraint("result IN ('PASS', 'FAIL')", name=op.f('ck_reconciliation_results_result')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('fk_reconciliation_results_company_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation_results'))
    )
    op.create_index(op.f('ix_reconciliation_results_company_id'), 'reconciliation_results', ['company_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_results_company_id_run_at'), 'reconciliation_results', ['company_id', 'run_at'], unique=False)
    op.create_table('stock_items',
    sa.Column('stock_item_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('base_unit', sa.Text(), nullable=True),
    sa.Column('gst_rate', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tally_guid', sa.Text(), nullable=False),
    sa.Column('alter_id', sa.BigInteger(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('ACTIVE', 'MISSING_IN_TALLY', 'INACTIVE')", name=op.f('ck_stock_items_status')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('fk_stock_items_company_id')),
    sa.PrimaryKeyConstraint('stock_item_id', name=op.f('pk_stock_items')),
    sa.UniqueConstraint('company_id', 'stock_item_id', name=op.f('uq_stock_items_company_id_stock_item_id')),
    sa.UniqueConstraint('company_id', 'tally_guid', name=op.f('uq_stock_items_company_id_tally_guid'))
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('fk_user_roles_company_id')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], name=op.f('fk_user_roles_role_id')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_user_roles_user_id')),
    sa.PrimaryKeyConstraint('user_id', 'company_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_index(op.f('ix_user_roles_company_id'), 'user_roles', ['company_id'], unique=False)
    op.create_table('voucher_types',
    sa.Column('voucher_type_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('parent_voucher_type_id', sa.UUID(), nullable=True),
    sa.Column('parent_tally_guid', sa.Text(), nullable=True),
    sa.Column('reserved_name', sa.Text(), nullable=True),
    sa.Column('base_voucher_type', sa.Text(), nullable=False),
    sa.Column('resolution_status', sa.Text(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tally_guid', sa.Text(), nullable=False),
    sa.Column('alter_id', sa.BigInteger(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("base_voucher_type IN ('SALES', 'PURCHASE', 'RECEIPT', 'PAYMENT', 'CONTRA', 'JOURNAL', 'CREDIT_NOTE', 'DEBIT_NOTE', 'OTHER')", name=op.f('ck_voucher_types_base_voucher_type')),
    sa.CheckConstraint("resolution_status IN ('RESOLVED', 'UNRESOLVED')", name=op.f('ck_voucher_types_resolution_status')),
    sa.CheckConstraint("status IN ('ACTIVE', 'MISSING_IN_TALLY', 'INACTIVE')", name=op.f('ck_voucher_types_status')),
    sa.ForeignKeyConstraint(['company_id', 'parent_voucher_type_id'], ['voucher_types.company_id', 'voucher_types.voucher_type_id'], name=op.f('fk_voucher_types_company_id_parent_voucher_type_id')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('fk_voucher_types_company_id')),
    sa.PrimaryKeyConstraint('voucher_type_id', name=op.f('pk_voucher_types')),
    sa.UniqueConstraint('company_id', 'tally_guid', name=op.f('uq_voucher_types_company_id_tally_guid')),
    sa.UniqueConstraint('company_id', 'voucher_type_id', name=op.f('uq_voucher_types_company_id_voucher_type_id'))
    )
    op.create_table('agent_commands',
    sa.Column('command_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('command_type', sa.Text(), nullable=False),
    sa.Column('sync_mode', sa.Text(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("command_type IN ('RUN_SYNC')", name=op.f('ck_agent_commands_command_type')),
    sa.CheckConstraint("status IN ('PENDING', 'CLAIMED', 'RUNNING', 'COMPLETED', 'FAILED', 'EXPIRED', 'FAILED_AGENT_LOST')", name=op.f('ck_agent_commands_status')),
    sa.CheckConstraint("sync_mode <> 'DATE_RANGE' OR (date_from IS NOT NULL AND date_to IS NOT NULL AND date_from <= date_to)", name=op.f('ck_agent_commands_date_range')),
    sa.CheckConstraint("sync_mode IN ('FULL', 'INCREMENTAL', 'DATE_RANGE', 'RECONCILIATION')", name=op.f('ck_agent_commands_sync_mode')),
    sa.ForeignKeyConstraint(['company_id', 'agent_id'], ['agents.company_id', 'agents.agent_id'], name=op.f('fk_agent_commands_company_id_agent_id')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('fk_agent_commands_company_id')),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name=op.f('fk_agent_commands_created_by')),
    sa.PrimaryKeyConstraint('command_id', name=op.f('pk_agent_commands')),
    sa.UniqueConstraint('company_id', 'command_id', name=op.f('uq_agent_commands_company_id_command_id'))
    )
    op.create_index(op.f('ix_agent_commands_agent_id_status'), 'agent_commands', ['agent_id', 'status'], unique=False)
    op.create_index(op.f('ix_agent_commands_company_id'), 'agent_commands', ['company_id'], unique=False)
    op.create_index(op.f('ix_agent_commands_status_created_at'), 'agent_commands', ['status', 'created_at'], unique=False)
    op.create_table('ledgers',
    sa.Column('ledger_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('parent_group_tally_guid', sa.Text(), nullable=True),
    sa.Column('primary_group_id', sa.UUID(), nullable=True),
    sa.Column('predefined_group_id', sa.UUID(), nullable=True),
    sa.Column('classification_group_id', sa.UUID(), nullable=True),
    sa.Column('is_bill_wise', sa.Boolean(), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tally_guid', sa.Text(), nullable=False),
    sa.Column('alter_id', sa.BigInteger(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('ACTIVE', 'MISSING_IN_TALLY', 'INACTIVE')", name=op.f('ck_ledgers_status')),
    sa.ForeignKeyConstraint(['company_id', 'classification_group_id'], ['groups.company_id', 'groups.group_id'], name=op.f('fk_ledgers_company_id_classification_group_id')),
    sa.ForeignKeyConstraint(['company_id', 'group_id'], ['groups.company_id', 'groups.group_id'], name=op.f('fk_ledgers_company_id_group_id')),
    sa.ForeignKeyConstraint(['company_id', 'predefined_group_id'], ['groups.company_id', 'groups.group_id'], name=op.f('fk_ledgers_company_id_predefined_group_id')),
    sa.ForeignKeyConstraint(['company_id', 'primary_group_id'], ['groups.company_id', 'groups.group_id'], name=op.f('fk_ledgers_company_id_primary_group_id')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('fk_ledgers_company_id')),
    sa.PrimaryKeyConstraint('ledger_id', name=op.f('pk_ledgers')),
    sa.UniqueConstraint('company_id', 'ledger_id', name=op.f('uq_ledgers_company_id_ledger_id')),
    sa.UniqueConstraint('company_id', 'tally_guid', name=op.f('uq_ledgers_company_id_tally_guid'))
    )
    op.create_index(op.f('ix_ledgers_company_id_classification_group_id'), 'ledgers', ['company_id', 'classification_group_id'], unique=False)
    op.create_index(op.f('ix_ledgers_company_id_primary_group_id'), 'ledgers', ['company_id', 'primary_group_id'], unique=False)
    op.create_table('stock_opening_balances',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('stock_item_id', sa.UUID(), nullable=False),
    sa.Column('financial_year_start', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['company_id', 'stock_item_id'], ['stock_items.company_id', 'stock_items.stock_item_id'], name=op.f('fk_stock_opening_balances_company_id_stock_item_id')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('fk_stock_opening_balances_company_id')),
    sa.PrimaryKeyConstraint('stock_item_id', 'financial_year_start', name=op.f('pk_stock_opening_balances'))
    )
    op.create_index(op.f('ix_stock_opening_balances_company_id'), 'stock_opening_balances', ['company_id'], unique=False)
    op.create_table('sync_schedules',
    sa.Column('schedule_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('cron_expression', sa.Text(), nullable=False),
    sa.Column('sync_mode', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("sync_mode IN ('FULL', 'INCREMENTAL', 'DATE_RANGE', 'RECONCILIATION')", name=op.f('ck_sync_schedules_sync_mode')),
    sa.ForeignKeyConstraint(['company_id', 'agent_id'], ['agents.company_id', 'agents.agent_id'], name=op.f('fk_sync_schedules_company_id_agent_id')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('fk_sync_schedules_company_id')),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name=op.f('fk_sync_schedules_created_by')),
    sa.PrimaryKeyConstraint('schedule_id', name=op.f('pk_sync_schedules'))
    )
    op.create_index(op.f('ix_sync_schedules_company_id'), 'sync_schedules', ['company_id'], unique=False)
    op.create_table('sync_watermarks',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('collection_type', sa.Text(), nullable=False),
    sa.Column('last_alter_id', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_successful_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), server_default='NEVER_SYNCED', nullable=False),
    sa.Column('locked_by_agent_id', sa.UUID(), nullable=True),
    sa.Column('lock_acquired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lock_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("collection_type IN ('COMPANY', 'GROUP', 'LEDGER', 'VOUCHER_TYPE', 'STOCK_ITEM', 'COST_CENTRE', 'VOUCHER')", name=op.f('ck_sync_watermarks_collection_type')),
    sa.CheckConstraint("status IN ('NEVER_SYNCED', 'OK', 'FAILED')", name=op.f('ck_sync_watermarks_status')),
    sa.ForeignKeyConstraint(['company_id', 'locked_by_agent_id'], ['agents.company_id', 'agents.agent_id'], name=op.f('fk_sync_watermarks_company_id_locked_by_agent_id')),
    sa.PrimaryKeyConstraint('company_id', 'collection_type', name=op.f('pk_sync_watermarks'))
    )
    op.create_table('vouchers',
    sa.Column('voucher_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('voucher_number', sa.Text(), nullable=True),
    sa.Column('voucher_type_id', sa.UUID(), nullable=False),
    sa.Column('voucher_date', sa.Date(), nullable=False),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tally_guid', sa.Text(), nullable=False),
    sa.Column('alter_id', sa.BigInteger(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('ACTIVE', 'CANCELLED', 'MISSING_IN_TALLY')", name=op.f('ck_vouchers_status')),
    sa.ForeignKeyConstraint(['company_id', 'voucher_type_id'], ['voucher_types.company_id', 'voucher_types.voucher_type_id'], name=op.f('fk_vouchers_company_id_voucher_type_id')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('fk_vouchers_company_id')),
    sa.PrimaryKeyConstraint('voucher_id', name=op.f('pk_vouchers')),
    sa.UniqueConstraint('company_id', 'tally_guid', name=op.f('uq_vouchers_company_id_tally_guid')),
    sa.UniqueConstraint('company_id', 'voucher_id', name=op.f('uq_vouchers_company_id_voucher_id'))
    )
    op.create_index(op.f('ix_vouchers_company_id_alter_id'), 'vouchers', ['company_id', 'alter_id'], unique=False)
    op.create_index(op.f('ix_vouchers_company_id_voucher_date'), 'vouchers', ['company_id', 'voucher_date'], unique=False)
    op.create_index(op.f('ix_vouchers_company_id_voucher_type_id_voucher_date'), 'vouchers', ['company_id', 'voucher_type_id', 'voucher_date'], unique=False)
    op.create_table('ledger_opening_balances',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('ledger_id', sa.UUID(), nullable=False),
    sa.Column('financial_year_start', sa.Date(), nullable=False),
    sa.Column('amount_absolute', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('accounting_direction', sa.Text(), nullable=False),
    sa.CheckConstraint("accounting_direction IN ('DEBIT', 'CREDIT')", name=op.f('ck_ledger_opening_balances_accounting_direction')),
    sa.CheckConstraint('amount_absolute >= 0', name=op.f('ck_ledger_opening_balances_amount_absolute')),
    sa.ForeignKeyConstraint(['company_id', 'ledger_id'], ['ledgers.company_id', 'ledgers.ledger_id'], name=op.f('fk_ledger_opening_balances_company_id_ledger_id')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('fk_ledger_opening_balances_company_id')),
    sa.PrimaryKeyConstraint('ledger_id', 'financial_year_start', name=op.f('pk_ledger_opening_balances'))
    )
    op.create_index(op.f('ix_ledger_opening_balances_company_id'), 'ledger_opening_balances', ['company_id'], unique=False)
    op.create_table('opening_bill_allocations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('ledger_id', sa.UUID(), nullable=False),
    sa.Column('reference_name', sa.Text(), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('amount_absolute', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('accounting_direction', sa.Text(), nullable=False),
    sa.Column('financial_year_start', sa.Date(), nullable=False),
    sa.CheckConstraint("accounting_direction IN ('DEBIT', 'CREDIT')", name=op.f('ck_opening_bill_allocations_accounting_direction')),
    sa.CheckConstraint('amount_absolute >= 0', name=op.f('ck_opening_bill_allocations_amount_absolute')),
    sa.ForeignKeyConstraint(['company_id', 'ledger_id'], ['ledgers.company_id', 'ledgers.ledger_id'], name=op.f('fk_opening_bill_allocations_company_id_ledger_id')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('fk_opening_bill_allocations_company_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opening_bill_allocations')),
    sa.UniqueConstraint('company_id', 'ledger_id', 'financial_year_start', 'reference_name', name='uq_opening_bill_allocations_bill')
    )
    op.create_index(op.f('ix_opening_bill_allocations_company_id'), 'opening_bill_allocations', ['company_id'], unique=False)
    op.create_table('sync_runs',
    sa.Column('sync_run_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('command_id', sa.UUID(), nullable=True),
    sa.Column('sync_mode', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('records_fetched', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('records_failed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint("status IN ('IN_PROGRESS', 'COMPLETED', 'FAILED', 'PARTIAL')", name=op.f('ck_sync_runs_status')),
    sa.CheckConstraint("sync_mode IN ('FULL', 'INCREMENTAL', 'DATE_RANGE', 'RECONCILIATION')", name=op.f('ck_sync_runs_sync_mode')),
    sa.ForeignKeyConstraint(['company_id', 'agent_id'], ['agents.company_id', 'agents.agent_id'], name=op.f('fk_sync_runs_company_id_agent_id')),
    sa.ForeignKeyConstraint(['company_id', 'command_id'], ['agent_commands.company_id', 'agent_commands.command_id'], name=op.f('fk_sync_runs_company_id_command_id')),
    sa.PrimaryKeyConstraint('sync_run_id', name=op.f('pk_sync_runs')),
    sa.UniqueConstraint('company_id', 'sync_run_id', name=op.f('uq_sync_runs_company_id_sync_run_id'))
    )
    op.create_index(op.f('ix_sync_runs_company_id_started_at'), 'sync_runs', ['company_id', 'started_at'], unique=False)
    op.create_table('voucher_entries',
    sa.Column('voucher_entry_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('voucher_id', sa.UUID(), nullable=False),
    sa.Column('ledger_id', sa.UUID(), nullable=False),
    sa.Column('line_sequence', sa.Integer(), nullable=False),
    sa.Column('stable_line_id', sa.Text(), nullable=True),
    sa.Column('amount_raw', sa.Text(), nullable=False),
    sa.Column('is_debit', sa.Boolean(), nullable=False),
    sa.Column('amount_absolute', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('amount_signed', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('accounting_direction', sa.Text(), nullable=False),
    sa.CheckConstraint("accounting_direction IN ('DEBIT', 'CREDIT')", name=op.f('ck_voucher_entries_accounting_direction')),
    sa.CheckConstraint("amount_signed = CASE WHEN accounting_direction = 'DEBIT' THEN amount_absolute ELSE -amount_absolute END", name=op.f('ck_voucher_entries_amount_signed')),
    sa.CheckConstraint("is_debit = (accounting_direction = 'DEBIT')", name=op.f('ck_voucher_entries_is_debit')),
    sa.CheckConstraint('amount_absolute >= 0', name=op.f('ck_voucher_entries_amount_absolute')),
    sa.ForeignKeyConstraint(['company_id', 'ledger_id'], ['ledgers.company_id', 'ledgers.ledger_id'], name=op.f('fk_voucher_entries_company_id_ledger_id')),
    sa.ForeignKeyConstraint(['company_id', 'voucher_id'], ['vouchers.company_id', 'vouchers.voucher_id'], name=op.f('fk_voucher_entries_company_id_voucher_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('voucher_entry_id', name=op.f('pk_voucher_entries')),
    sa.UniqueConstraint('company_id', 'voucher_entry_id', name=op.f('uq_voucher_entries_company_id_voucher_entry_id'))
    )
    op.create_index(op.f('ix_voucher_entries_company_id_ledger_id'), 'voucher_entries', ['company_id', 'ledger_id'], unique=False)
    op.create_index(op.f('ix_voucher_entries_voucher_id'), 'voucher_entries', ['voucher_id'], unique=False)
    op.create_table('voucher_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('voucher_id', sa.UUID(), nullable=False),
    sa.Column('stock_item_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('rate', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['company_id', 'stock_item_id'], ['stock_items.company_id', 'stock_items.stock_item_id'], name=op.f('fk_voucher_items_company_id_stock_item_id')),
    sa.ForeignKeyConstraint(['company_id', 'voucher_id'], ['vouchers.company_id', 'vouchers.voucher_id'], name=op.f('fk_voucher_items_company_id_voucher_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voucher_items'))
    )
    op.create_index(op.f('ix_voucher_items_stock_item_id'), 'voucher_items', ['stock_item_id'], unique=False)
    op.create_index(op.f('ix_voucher_items_voucher_id'), 'voucher_items', ['voucher_id'], unique=False)
    op.create_table('bill_allocations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('voucher_entry_id', sa.Integer(), nullable=False),
    sa.Column('ledger_id', sa.UUID(), nullable=False),
    sa.Column('allocation_type_raw', sa.Text(), nullable=True),
    sa.Column('allocation_type', sa.Text(), nullable=False),
    sa.Column('reference_name', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('amount_absolute', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('accounting_direction', sa.Text(), nullable=False),
    sa.CheckConstraint("accounting_direction IN ('DEBIT', 'CREDIT')", name=op.f('ck_bill_allocations_accounting_direction')),
    sa.CheckConstraint("allocation_type IN ('NEW_REF', 'AGST_REF', 'ADVANCE', 'ON_ACCOUNT', 'UNSUPPORTED')", name=op.f('ck_bill_allocations_allocation_type')),
    sa.CheckConstraint('amount_absolute >= 0', name=op.f('ck_bill_allocations_amount_absolute')),
    sa.ForeignKeyConstraint(['company_id', 'ledger_id'], ['ledgers.company_id', 'ledgers.ledger_id'], name=op.f('fk_bill_allocations_company_id_ledger_id')),
    sa.ForeignKeyConstraint(['company_id', 'voucher_entry_id'], ['voucher_entries.company_id', 'voucher_entries.voucher_entry_id'], name=op.f('fk_bill_allocations_company_id_voucher_entry_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bill_allocations'))
    )
    op.create_index(op.f('ix_bill_allocations_company_id_ledger_id_reference_name'), 'bill_allocations', ['company_id', 'ledger_id', 'reference_name'], unique=False)
    op.create_index(op.f('ix_bill_allocations_due_date'), 'bill_allocations', ['due_date'], unique=False)
    op.create_index(op.f('ix_bill_allocations_voucher_entry_id'), 'bill_allocations', ['voucher_entry_id'], unique=False)
    op.create_table('cost_centre_allocations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('voucher_entry_id', sa.Integer(), nullable=False),
    sa.Column('cost_centre_id', sa.UUID(), nullable=False),
    sa.Column('amount_absolute', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.CheckConstraint('amount_absolute >= 0', name=op.f('ck_cost_centre_allocations_amount_absolute')),
    sa.ForeignKeyConstraint(['company_id', 'cost_centre_id'], ['cost_centres.company_id', 'cost_centres.cost_centre_id'], name=op.f('fk_cost_centre_allocations_company_id_cost_centre_id')),
    sa.ForeignKeyConstraint(['company_id', 'voucher_entry_id'], ['voucher_entries.company_id', 'voucher_entries.voucher_entry_id'], name=op.f('fk_cost_centre_allocations_company_id_voucher_entry_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cost_centre_allocations'))
    )
    op.create_index(op.f('ix_cost_centre_allocations_voucher_entry_id'), 'cost_centre_allocations', ['voucher_entry_id'], unique=False)
    op.create_table('stock_snapshots',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('stock_item_id', sa.UUID(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('closing_quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('sync_run_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id', 'stock_item_id'], ['stock_items.company_id', 'stock_items.stock_item_id'], name=op.f('fk_stock_snapshots_company_id_stock_item_id')),
    sa.ForeignKeyConstraint(['company_id', 'sync_run_id'], ['sync_runs.company_id', 'sync_runs.sync_run_id'], name=op.f('fk_stock_snapshots_company_id_sync_run_id')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('fk_stock_snapshots_company_id')),
    sa.PrimaryKeyConstraint('stock_item_id', 'as_of_date', name=op.f('pk_stock_snapshots'))
    )
    op.create_index(op.f('ix_stock_snapshots_company_id'), 'stock_snapshots', ['company_id'], unique=False)
    op.create_table('sync_batches',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('sync_run_id', sa.UUID(), nullable=False),
    sa.Column('collection_type', sa.Text(), nullable=False),
    sa.Column('batch_seq', sa.Integer(), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted', sa.Integer(), nullable=False),
    sa.Column('rejected_stale', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.CheckConstraint("collection_type IN ('COMPANY', 'GROUP', 'LEDGER', 'VOUCHER_TYPE', 'STOCK_ITEM', 'COST_CENTRE', 'VOUCHER')", name=op.f('ck_sync_batches_collection_type')),
    sa.ForeignKeyConstraint(['company_id', 'sync_run_id'], ['sync_runs.company_id', 'sync_runs.sync_run_id'], name=op.f('fk_sync_batches_company_id_sync_run_id')),
    sa.PrimaryKeyConstraint('batch_id', name=op.f('pk_sync_batches'))
    )
    op.create_table('sync_errors',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('sync_run_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('tally_guid', sa.Text(), nullable=True),
    sa.Column('error_code', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id', 'sync_run_id'], ['sync_runs.company_id', 'sync_runs.sync_run_id'], name=op.f('fk_sync_errors_company_id_sync_run_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_errors'))
    )
    op.create_index(op.f('ix_sync_errors_sync_run_id'), 'sync_errors', ['sync_run_id'], unique=False)
    # ### end Alembic commands ###
    _upgrade_extras()


def downgrade() -> None:
    _downgrade_extras()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_errors_sync_run_id'), table_name='sync_errors')
    op.drop_table('sync_errors')
    op.drop_table('sync_batches')
    op.drop_index(op.f('ix_stock_snapshots_company_id'), table_name='stock_snapshots')
    op.drop_table('stock_snapshots')
    op.drop_index(op.f('ix_cost_centre_allocations_voucher_entry_id'), table_name='cost_centre_allocations')
    op.drop_table('cost_centre_allocations')
    op.drop_index(op.f('ix_bill_allocations_voucher_entry_id'), table_name='bill_allocations')
    op.drop_index(op.f('ix_bill_allocations_due_date'), table_name='bill_allocations')
    op.drop_index(op.f('ix_bill_allocations_company_id_ledger_id_reference_name'), table_name='bill_allocations')
    op.drop_table('bill_allocations')
    op.drop_index(op.f('ix_voucher_items_voucher_id'), table_name='voucher_items')
    op.drop_index(op.f('ix_voucher_items_stock_item_id'), table_name='voucher_items')
    op.drop_table('voucher_items')
    op.drop_index(op.f('ix_voucher_entries_voucher_id'), table_name='voucher_entries')
    op.drop_index(op.f('ix_voucher_entries_company_id_ledger_id'), table_name='voucher_entries')
    op.drop_table('voucher_entries')
    op.drop_index(op.f('ix_sync_runs_company_id_started_at'), table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_opening_bill_allocations_company_id'), table_name='opening_bill_allocations')
    op.drop_table('opening_bill_allocations')
    op.drop_index(op.f('ix_ledger_opening_balances_company_id'), table_name='ledger_opening_balances')
    op.drop_table('ledger_opening_balances')
    op.drop_index(op.f('ix_vouchers_company_id_voucher_type_id_voucher_date'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_company_id_voucher_date'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_company_id_alter_id'), table_name='vouchers')
    op.drop_table('vouchers')
    op.drop_table('sync_watermarks')
    op.drop_index(op.f('ix_sync_schedules_company_id'), table_name='sync_schedules')
    op.drop_table('sync_schedules')
    op.drop_index(op.f('ix_stock_opening_balances_company_id'), table_name='stock_opening_balances')
    op.drop_table('stock_opening_balances')
    op.drop_index(op.f('ix_ledgers_company_id_primary_group_id'), table_name='ledgers')
    op.drop_index(op.f('ix_ledgers_company_id_classification_group_id'), table_name='ledgers')
    op.drop_table('ledgers')
    op.drop_index(op.f('ix_agent_commands_status_created_at'), table_name='agent_commands')
    op.drop_index(op.f('ix_agent_commands_company_id'), table_name='agent_commands')
    op.drop_index(op.f('ix_agent_commands_agent_id_status'), table_name='agent_commands')
    op.drop_table('agent_commands')
    op.drop_table('voucher_types')
    op.drop_index(op.f('ix_user_roles_company_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_table('stock_items')
    op.drop_index(op.f('ix_reconciliation_results_company_id_run_at'), table_name='reconciliation_results')
    op.drop_index(op.f('ix_reconciliation_results_company_id'), table_name='reconciliation_results')
    op.drop_table('reconciliation_results')
    op.drop_index('uq_groups_company_id_reserved_name', table_name='groups', postgresql_where=sa.text('reserved_name IS NOT NULL'))
    op.drop_index(op.f('ix_groups_primary_group_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_table('cost_centres')
    op.drop_index(op.f('ix_agents_company_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_agent_registration_tokens_company_id'), table_name='agent_registration_tokens')
    op.drop_table('agent_registration_tokens')
    op.drop_index('uq_users_email_lower', table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('companies')
    # ### end Alembic commands ###


# --- hand-written: seeds, triggers and grants (autogenerate cannot express them) ---


# ERRCODE 23001 (restrict_violation) surfaces as IntegrityError in the application.
AGENT_COMMAND_OWNER = """
CREATE FUNCTION agent_commands_immutable_owner() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.agent_id IS DISTINCT FROM OLD.agent_id
       OR NEW.company_id IS DISTINCT FROM OLD.company_id THEN
        RAISE EXCEPTION 'agent_commands.agent_id and company_id cannot change (RTE-1.4)'
            USING ERRCODE = '23001';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER agent_commands_immutable_owner BEFORE UPDATE ON agent_commands
    FOR EACH ROW EXECUTE FUNCTION agent_commands_immutable_owner();
"""

# Synced records are never hard-deleted (SRS 5.1-5, DR-ML-1); lifecycle is a status change.
# Row triggers do not fire on TRUNCATE, which only the owner role may run.
NO_DELETE_TABLES = [
    "groups",
    "ledgers",
    "voucher_types",
    "stock_items",
    "cost_centres",
    "vouchers",
]
FORBID_DELETE = """
CREATE FUNCTION forbid_delete() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION '% rows are never deleted; change status instead (SRS 5.1-5, DR-ML-1)',
        TG_TABLE_NAME USING ERRCODE = '23001';
END $$;
"""


def _upgrade_extras() -> None:
    op.execute(AGENT_COMMAND_OWNER)
    op.execute(FORBID_DELETE)
    for table in NO_DELETE_TABLES:
        op.execute(
            f"CREATE TRIGGER {table}_forbid_delete BEFORE DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION forbid_delete()"
        )
    roles = sa.table("roles", sa.column("role_id", sa.SmallInteger), sa.column("role_name"))
    op.bulk_insert(
        roles,
        [
            {"role_id": 1, "role_name": "OWNER"},
            {"role_id": 2, "role_name": "ACCOUNTANT"},
            {"role_id": 3, "role_name": "ADMIN"},
        ],
    )


def _downgrade_extras() -> None:
    for table in NO_DELETE_TABLES:
        op.execute(f"DROP TRIGGER {table}_forbid_delete ON {table}")
    op.execute("DROP FUNCTION forbid_delete()")
    op.execute("DROP TRIGGER agent_commands_immutable_owner ON agent_commands")
    op.execute("DROP FUNCTION agent_commands_immutable_owner()")
