"""Refresh-token rotation table and the login-throttle index (Phase 2, D-033).

Autogenerated from app.models, hand-reviewed (2026-09-25). tally_app gets DML on the new
table through the default privileges in deploy/postgres/grants.sql.

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-25 11:44:53.018200
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### autogenerated from app.models, hand-reviewed ###
    op.create_table('refresh_tokens',
    sa.Column('jti', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_refresh_tokens_user_id')),
    sa.PrimaryKeyConstraint('jti', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index('ix_audit_logs_login_entity_id_created_at', 'audit_logs', ['entity_id', 'created_at'], unique=False, postgresql_where=sa.text("action = 'LOGIN'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### autogenerated from app.models, hand-reviewed ###
    op.drop_index('ix_audit_logs_login_entity_id_created_at', table_name='audit_logs', postgresql_where=sa.text("action = 'LOGIN'"))
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
