"""Command error code, and at most one command in progress per Agent (Phase 3, D-035).

Autogenerated from app.models, hand-reviewed (2026-09-25). The partial unique index is what
makes "one command at a time" race-proof (D-035 #13).

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-25 12:22:39.767265
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### autogenerated from app.models, hand-reviewed ###
    op.add_column('agent_commands', sa.Column('error_code', sa.Text(), nullable=True))
    op.create_index('uq_agent_commands_one_active', 'agent_commands', ['agent_id'], unique=True, postgresql_where=sa.text("status IN ('CLAIMED', 'RUNNING')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### autogenerated from app.models, hand-reviewed ###
    op.drop_index('uq_agent_commands_one_active', table_name='agent_commands', postgresql_where=sa.text("status IN ('CLAIMED', 'RUNNING')"))
    op.drop_column('agent_commands', 'error_code')
    # ### end Alembic commands ###
