"""Deterministic command order and schedule firing (Phase 3, D-036).

Autogenerated from app.models, hand-reviewed (2026-09-25). `seq` is an identity column, so
existing commands get values when it is added; oldest = (created_at, seq).

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-25 12:37:36.099732
"""
from alembic import op
import sqlalchemy as sa


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### autogenerated from app.models, hand-reviewed ###
    op.add_column('agent_commands', sa.Column('seq', sa.BigInteger(), sa.Identity(always=True), nullable=False))
    op.add_column('sync_schedules', sa.Column('next_fire_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_sync_schedules_next_fire_at'), 'sync_schedules', ['next_fire_at'], unique=False, postgresql_where=sa.text('is_active'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### autogenerated from app.models, hand-reviewed ###
    op.drop_index(op.f('ix_sync_schedules_next_fire_at'), table_name='sync_schedules', postgresql_where=sa.text('is_active'))
    op.drop_column('sync_schedules', 'next_fire_at')
    op.drop_column('agent_commands', 'seq')
    # ### end Alembic commands ###
