"""Books-beginning date and watermark holds for failing records (Phase 5, D-039 #5, #7).

Autogenerated from app.models, hand-reviewed (2026-09-27).

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-27 10:31:29.855040
"""
from alembic import op
import sqlalchemy as sa


revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### autogenerated from app.models, hand-reviewed ###
    op.add_column('companies', sa.Column('books_from', sa.Date(), nullable=True))
    op.add_column('sync_errors', sa.Column('alter_id', sa.BigInteger(), nullable=True))
    op.add_column('sync_errors', sa.Column('watermark_hold', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_sync_errors_company_id_entity_type_watermark_hold'), 'sync_errors', ['company_id', 'entity_type', 'watermark_hold'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### autogenerated from app.models, hand-reviewed ###
    op.drop_index(op.f('ix_sync_errors_company_id_entity_type_watermark_hold'), table_name='sync_errors')
    op.drop_column('sync_errors', 'watermark_hold')
    op.drop_column('sync_errors', 'alter_id')
    op.drop_column('companies', 'books_from')
    # ### end Alembic commands ###
