"""Key lists for deletion detection and a group's own nature (Phase 6, D-041).

Autogenerated from app.models, hand-reviewed (2026-09-27): the CHECK on groups.own_nature is
added by hand (autogenerate does not see new checks on existing tables).

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-27 14:47:32.431820
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### autogenerated from app.models, hand-reviewed ###
    op.create_table('sync_key_lists',
    sa.Column('list_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('sync_run_id', sa.UUID(), nullable=False),
    sa.Column('collection_type', sa.Text(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('received_chunks', postgresql.ARRAY(sa.Integer()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('final_seq', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), server_default='RECEIVING', nullable=False),
    sa.Column('keys_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('candidates', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('marked_missing', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('reappeared', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('missed_changes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('guard_waived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('confirmed_by', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("collection_type IN ('COMPANY', 'GROUP', 'LEDGER', 'VOUCHER_TYPE', 'STOCK_ITEM', 'COST_CENTRE', 'VOUCHER')", name=op.f('ck_sync_key_lists_collection_type')),
    sa.CheckConstraint("status IN ('RECEIVING', 'APPLIED', 'SUSPICIOUS', 'CONFIRMED', 'ABANDONED')", name=op.f('ck_sync_key_lists_status')),
    sa.ForeignKeyConstraint(['company_id', 'sync_run_id'], ['sync_runs.company_id', 'sync_runs.sync_run_id'], name=op.f('fk_sync_key_lists_company_id_sync_run_id')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('fk_sync_key_lists_company_id')),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.user_id'], name=op.f('fk_sync_key_lists_confirmed_by')),
    sa.PrimaryKeyConstraint('list_id', name=op.f('pk_sync_key_lists')),
    sa.UniqueConstraint('company_id', 'list_id', name=op.f('uq_sync_key_lists_company_id_list_id'))
    )
    op.create_index(op.f('ix_sync_key_lists_company_id_collection_type_evaluated_at'), 'sync_key_lists', ['company_id', 'collection_type', 'evaluated_at'], unique=False)
    op.create_table('sync_key_list_keys',
    sa.Column('list_id', sa.UUID(), nullable=False),
    sa.Column('tally_guid', sa.Text(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('alter_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['company_id', 'list_id'], ['sync_key_lists.company_id', 'sync_key_lists.list_id'], name=op.f('fk_sync_key_list_keys_company_id_list_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('fk_sync_key_list_keys_company_id')),
    sa.PrimaryKeyConstraint('list_id', 'tally_guid', name=op.f('pk_sync_key_list_keys'))
    )
    op.add_column('groups', sa.Column('own_nature', sa.Text(), nullable=True))
    op.create_check_constraint(op.f('ck_groups_own_nature'), 'groups', "own_nature IN ('ASSET', 'LIABILITY', 'INCOME', 'EXPENSE')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### autogenerated from app.models, hand-reviewed ###
    op.drop_constraint(op.f('ck_groups_own_nature'), 'groups', type_='check')
    op.drop_column('groups', 'own_nature')
    op.drop_table('sync_key_list_keys')
    op.drop_index(op.f('ix_sync_key_lists_company_id_collection_type_evaluated_at'), table_name='sync_key_lists')
    op.drop_table('sync_key_lists')
    # ### end Alembic commands ###
