"""Reconciliation: Tally's values staged per run, results by run, runs' reconciled_at (P10, D-048).

Autogenerated from app.models, hand-reviewed (2026-09-29).

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-29 11:45:05.274782
"""
from alembic import op
import sqlalchemy as sa


revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### autogenerated from app.models, hand-reviewed ###
    op.create_table('reconciliation_tally_values',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('sync_run_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('entity_guid', sa.Text(), nullable=False),
    sa.Column('voucher_type_guid', sa.Text(), server_default='', nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('credit', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.CheckConstraint("kind IN ('TOTAL', 'LEDGER_CLOSING', 'STOCK_CLOSING')", name=op.f('ck_reconciliation_tally_values_kind')),
    sa.ForeignKeyConstraint(['company_id', 'sync_run_id'], ['sync_runs.company_id', 'sync_runs.sync_run_id'], name=op.f('fk_reconciliation_tally_values_company_id_sync_run_id')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('fk_reconciliation_tally_values_company_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation_tally_values')),
    sa.UniqueConstraint('sync_run_id', 'kind', 'entity_guid', 'voucher_type_guid', 'period_start', 'period_end', name='uq_reconciliation_tally_values_key')
    )
    op.add_column('reconciliation_results', sa.Column('sync_run_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_reconciliation_results_sync_run_id'), 'reconciliation_results', ['sync_run_id'], unique=False)
    op.create_foreign_key(op.f('fk_reconciliation_results_company_id_sync_run_id'), 'reconciliation_results', 'sync_runs', ['company_id', 'sync_run_id'], ['company_id', 'sync_run_id'])
    op.add_column('sync_runs', sa.Column('reconciled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### autogenerated from app.models, hand-reviewed ###
    op.drop_column('sync_runs', 'reconciled_at')
    op.drop_constraint(op.f('fk_reconciliation_results_company_id_sync_run_id'), 'reconciliation_results', type_='foreignkey')
    op.drop_index(op.f('ix_reconciliation_results_sync_run_id'), table_name='reconciliation_results')
    op.drop_column('reconciliation_results', 'sync_run_id')
    op.drop_table('reconciliation_tally_values')
    # ### end Alembic commands ###
